### ISSUE TITLE
Please remove execute bit from text files

### ISSUE THREAD

**Issue by jtgoral** [igagis/prorab#28] opened 2018-01-03 15:11 UTC
After git clone all files have execute bit set.

**Comment by igagis** [comment] 2018-01-03 15:15
I could not reproduce this, after cloning only directories have execute bit set, files don't.
What environment do you use? Linux (which one?) or something else?

**Comment by igagis** [comment] 2018-01-07 18:54
closing the bug as unreproducible

**Closed by igagis** 2018-01-07 18:54 UTC
